### PR TITLE
recreate of pull request #2: update Readme.md, adding missing skill

### PR DESCRIPTION
**Pull request by Sarverott**
there was problems with reopening of previous pull request, so I create new one. previous: https://github.com/LilaLio/LilaLio/pull/2

### CODE REVIEW

**Comment by TheBACK001** [comment]
goofy ahh pull request

**Comment by Sarverott** [comment]
> goofy ahh pull request

¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Review by LilaLio — COMMENTED** [review]
LGTM

**Comment by TheBACK001** [comment]
BRO CAME BACK

**Comment by TheBACK001** [comment]
LETS GOOOOOO SHE MERGED

**Comment by TheBACK001** [comment]
WWWWWW

**Comment by shinyPy** [comment]
what is this 😭

**Comment by TheBACK001** [comment]
a pull request

**Comment by shinyPy** [comment]
understandable, have a good day

**Pull request merged**
