### PR TITLE
Update README.md, adding missing skill

### PR DESCRIPTION
**Pull request by Sarverott**
Very smart and clever method of followers count grow, by using propably API to follow and unfollow people, that many times follows back, without noticing this. 
Cool, I would never thought about that.

### CODE REVIEW

**Comment by LilaLio** [comment]
This is not my main account, I'm just seeing how many people will follow the bot and it logging changes each hours.

It's pretty interesting, the more followers it has, the easier it is to gain them. It seems that people prefer to base their following on this number and this false notoriety, it really is exponential.

**Comment by LilaLio** [comment]
If you reopen your pr I'll merge it because it's funny xD

**Comment by oPOCCOMAXAo** [comment]
Just reopen-reclose as fast as possible)

**Comment by Sarverott** [comment]
> If you reopen your pr I'll merge it because it's funny xD

Ok then, give me a sec xd

**Comment by Sarverott** [comment]
> Just reopen-reclose as fast as possible)

Not this time xd as comments in PR#4 shows this case starts to be serious.

But we can spawn some open-close dance PRs in near future if @LilaLio don't show and brag about code of that bot of his/her to us XD

**Pull request closed without merging**
